// taskflow-angular/src/app/shared/ui/progress-bar.ts
import { Component, input } from "@angular/core";

@Component({
  selector: "tf-progress-bar",
  template: `
    <div
      class="track"
      role="progressbar"
      [attr.aria-label]="label()"
      [attr.aria-valuenow]="value()"
      aria-valuemin="0"
      aria-valuemax="100"
    >
      <div
        class="fill"
        [style.width.%]="clamped()"
        [style.background]="color()"
      ></div>
    </div>
  `,
  styles: `
    .track {
      height: 0.375rem;
      overflow: hidden;
      border-radius: 999px;
      background: var(--tf-subtle);
    }
    .fill {
      height: 100%;
      border-radius: inherit;
    }
  `,
})
export class ProgressBar {
  readonly value = input(0);
  readonly color = input("var(--tf-accent)");
  readonly label = input("Progress");

  clamped(): number {
    return Math.min(100, Math.max(0, this.value()));
  }
}

// components/demos/taskflow/ui/ProgressBar.tsx
"use client";

import { motion } from "framer-motion";
import { cn } from "@/lib/demos/taskflow/utils";

export function ProgressBar({
  value,
  className,
  color,
}: {
  value: number;
  className?: string;
  color?: string;
}) {
  const clamped = Math.max(0, Math.min(100, value));
  return (
    <div
      className={cn("h-1.5 overflow-hidden rounded-full bg-subtle-strong", className)}
      role="progressbar"
      aria-valuenow={clamped}
      aria-valuemin={0}
      aria-valuemax={100}
    >
      <motion.div
        className="h-full rounded-full"
        style={{ background: color ?? "var(--accent)" }}
        initial={{ width: 0 }}
        whileInView={{ width: `${clamped}%` }}
        viewport={{ once: true }}
        transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
      />
    </div>
  );
}
